### ISSUE TITLE
Build DCE Demo & Test environments on AWS

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/MIRA#1]

**Comment by acozine** [comment]
As a first step, I have restarted the user acceptance testing box we used for the last round of MIRA updates as a reference build. You can reach it at either mira.curationexperts.com (the old name) or tufts.curationexperts.com (to match our current naming scheme). I will keep the DNS entry and replace the hardware it points to as I go.

**Comment by mark-dce** [comment]
@acozine we'll also need a Fedora 4 based environment capable of running a Hyrax application.  Can you set that up and work with @no-reply to choose a DNS name and get the repo setup for cap deploys.
