### ISSUE TITLE
Store user's display name rather than e-mail

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/MIRA#26]
Double check what's being stored as the user ID when a work is created.  The `User` model `.to_s` method might need updating.

see https://github.com/TuftsUniversity/MIRA/blob/ldap/app/models/user.rb#L13-L15

**Comment by no-reply** [comment]
`#to_s` currently aliases `#username`. We should confirm that this works with LDAP users like username: `mark` password : `mark1`.

If that is working fine, this can be closed but we need an additional (low priority) ticket to add access to the ldap email field.

**Comment by mark-dce** [comment]
See #64 - this may be covered by that work.

**Comment by mark-dce** [comment]
fixed in curationexperts/tufts_concerns#21
