### ISSUE TITLE
Add admin role behavior to tufts_concerns User model

### ISSUE THREAD

**Issue by no-reply** [curationexperts/MIRA#29]
The `User#admin?` method currently simply returns true. Fix this.

**Comment by mark-dce** [comment]
There's a roles table and a roles_users:

mysql> use hyd_mira;
Database changed
mysql> select * from roles;
+----+-------+
| id | name  |
+----+-------+
|  1 | admin |
+----+-------+
1 row in set (0.00 sec)


This gets managed in the UI through https://github.com/samvera/hydra-role-management

So in tufts_models app/models/concerns/tufts/user.rb:

```
# Connects this user object to Role behaviors.
  include Hydra::RoleManagement::UserRoles
```

Which defines admin?
app/models/concerns/hydra/role_management/user_roles.rb

 ```
def guest?
        if defined?(DeviseGuests)
          read_attribute :guest
        else
          false
        end
      end


      def admin?
        roles.where(name: 'admin').exists?
      end
```

I dunno the state of hydra-role-management if the /roles mounted UI piece doesn't exist in the Hyrax based version, we're fine just maintaining it In tables.

Mike

**Comment by mark-dce** [comment]
The following users can be used to login to LDAP

| User | Password |
| -------|---------------|
| mark | mark1 |
| alicia | alicia1 |
{ r_admin1 | r_admin1 |
| m_admin | m_admin1 |
| brian | brian1 |

Until #38 is fixed, you can manually enter  the `/users/sign_in`and '/users/sign_out' paths to change users.

**Comment by little9** [comment]
I removed the override method and the admin? method provided by Hydra:RoleMangagement:UserRoles works if you create the proper roles in the database: 

```
user = User.find(1)
user.roles.push(Role.new(id: 1, name: 'admin')
```

the change over is over at this branch: https://github.com/curationexperts/tufts_concerns/tree/fix/admin

I can do a PR, but folks will need to remember to create the role and association.

**Comment by mark-dce** [comment]
The  `admin` role gets created in MIRA from the database seed:
https://github.com/curationexperts/MIRA/blob/develop/db/seeds.rb#L15-L21

We might want to think about setting up a default admin user and a local ldap using ladle https://rubygems.org/gems/ladle/versions/1.0.1 in the development environment - Mike K. at Tufts has been using ladle successfully to provide ldap service for their test environment:
https://github.com/curationexperts/MIRA/blob/ldap/Gemfile#L66
https://github.com/curationexperts/MIRA/blob/ldap/spec/spec_helper.rb#L45
https://github.com/curationexperts/MIRA/blob/ldap/spec/fixtures/tufts_ldap.ldif
