### ISSUE TITLE
refine resque capabilities

### ISSUE THREAD

**Issue by acozine** [curationexperts/mira#308]
Offer greater support for the resque workers:
1. Mount resque admin in a secure way
2. Add resque_pool 
3. Add an init script
4. Add documentation for nagios monitoring for resque workers

**Comment by mark-dce** [comment]
Discussed with Tufts during Infrastructure Consolidation scoping and they indicated that their current process of manually mounting resque admin on an as-needed basis was sufficient

**Comment by acozine** [comment]
Added resque-pool to the code, to nagios, and to the cap deploy process for our convenience. Also added an init script to the AWS machines, but not to the code. I did not mount the resque admin page.
