### ISSUE TITLE
manage templates - clicking cancel deletes template

### ISSUE THREAD

**Issue by mkorcy** [curationexperts/mira#315]
So if you click manage templates, then click 'Edit' on a template, and then cancel out of the screen, cancelling out deletes the template.

Looks like this on the server:

Started DELETE "/records/template:14/cancel" for 10.250.108.11 at 2014-11-04 13:48:30 -0500
Processing by RecordsController#cancel as HTML

Confirmed this on mira.curationexperts.com

**Comment by acozine** [comment]
Tested today with the new code on devmira.curationexperts.com. Bug fixed.
