### ISSUE TITLE
Purge batch doesn't actually purge anything

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/mira#316]
This issue first noticed in the Tufts Dev. environment.

Purge batch doesn't actually purge the items in the batch. In order to purge the items, I have to go into each one separately, and select purge.

**Comment by acozine** [comment]
Tested 4/30/15 with the new MIRA code. Batch purge does purge objects now. If I have an existing batch, I can delete all items in that batch. To delete items that are not part of a pre-existing batch, I recommend:
1. Create a template called "To Be Purged" that adds the phrase "Purge This Object" as a secondary title. 
2. Search for objects you want to purge
3. Select the objects you want to purge from your results
4. Click Apply Template
5. Apply the "To Be Purged" template
6. Purge the resulting batch
