### ISSUE TITLE
if you click cancel while editing an object it deletes the object

### ISSUE THREAD

**Issue by mkorcy** [curationexperts/mira#321]

**Comment by mark-dce** [comment]
Same issue as #315 - unintended side-effect of deleting the PID when new object creation is cancelled.

**Comment by acozine** [comment]
Tested today on devmira.curationexperts.com. Bug fixed.

**Comment by jcoyne** [comment]
We didn't do anything anything to fix this bug, it's more a case of "Can't duplicate on our server". @mkorcy can you take a look and see if you can duplicate on your server?  The current code is expecting the DCA_META datastream to be versionable, so perhaps there are objects on your server where that is not true.

**Comment by mkorcy** [comment]
@jcoyne i couldn't reproduce this, i asked the original reporters but I never heard anything back.
