### ISSUE TITLE
Browser Testing

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#331]
Test for compatibility with browsers in SOW
a.	Firefox 31.4.0 ESR or current release at start of acceptance testing  
b.	Chrome - current release at start of acceptance testing
c.	Safari 7.1.2 or current release at start of acceptance testing

**Comment by mark-dce** [comment]
Blocked until final release candidate is available.

**Comment by jcoyne** [comment]
Issue with Firefox 38 on a Mac. When uploading a file, the mime-type check fails with "You provided a application/x-download file, which is not a valid type for Archival.pdf".  This is caused by Firefox sending the wrong Content-type headers. https://bugzilla.mozilla.org/show_bug.cgi?id=373621

**Comment by mark-dce** [comment]
Mark has completed demos and testing with Chrome

Alicia has used firefox throughout the development cycle

Mark, Justin, Val, Tony have used Safari throughout the development cycle
