### ISSUE TITLE
Gather / Validate we have sample content for testing and demo

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#332]
- [ ] 3+ samples of each content type:
    - [ ]  curatedCollection - not editable in MIRA, managed in TROVE - 1 personal / 2 course
    - [ ] TuftsAudio
    - [ ] TuftsAudioText
    - [ ] TuftsEad
    - [ ] TuftsGenericObject
    - [ ] TuftsImage
    - [ ] TuftsRcr
    - [ ] TuftsTei (to be added by pull request)
    - [ ] TuftsVideo (incorporated by Tufts via pull request)
    - [ ] TuftsVotingRecord
- [ ] Rake task or XML Import to rebuild empty repo

**Comment by mark-dce** [comment]
See #372 - rake task to build importable content from list of pids

**Comment by acozine** [comment]
@mkorcy sent a zipped archive of sample data and xml - they're in google drive under the current project as Sample Objects and/or the zipfile is on devmira in /opt
