### ISSUE TITLE
Create new objects in Draft namespace

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#333]
**FROM SOW**
INFRA-1
2.	Change MIRA to create new objects in the draft namespace rather than a separate Fedora instance
    a.	For user supplied PIDs, replace the user supplied namespace prefix with draft:, assume the published object will be prefixed tufts:

Create new objects as draft objects from
- [x] Single item Administrator create a new object
- [x] Single item Self deposit
- [x] Template ingest
- [x] XML ingest

**Comment by val99erie** [comment]
Question: What is the full set of models that we need draft objects for?

* TuftsAudio
* TuftsAudioText
* TuftsGenericObject
* TuftsImage
* TuftsPdf
* TuftsTEI

These models should not have draft objects, right?

* TuftsBase
* TuftsEAD
* TuftsTemplate
* TuftsVotingRecord
* TuftsRCR ??
* any type of collection

**Comment by mark-dce** [comment]
I think anything that inherits from TuftsBase should be capable of having a draft version.  EAD should (it's called 'Collection Guide' in the UI).  We don't currently support creation of TuftsRCR or TuftsVotingRecord objects via the UI, but I think that's just a case of Tufts not needing to edit those yet rather than a policy decision that they would never be handled in the MIRA UI.

If you just make drafts a behavior of all TuftsBase, that automatically excludes Templates and Collections which are the primary object types that drafts don't make sense for.

**Comment by val99erie** [comment]
Ok, from our chat on skype, here is what I think the correct list is.  This is what I'm going to code unless someone tells me otherwise:

These models need draft objects:

* TuftsAudio
* TuftsAudioText
* TuftsGenericObject
* TuftsImage
* TuftsPdf
* TuftsTEI
* TuftsEAD
* TuftsVotingRecord
* TuftsRCR

These models should not have draft objects:

* TuftsTemplate
* any type of collection

**Comment by mark-dce** [comment]
That looks like the right list - anything that you could end up with in search results in MIRA and get an edit link for needs to be able to saved as a draft.

**Comment by val99erie** [comment]
The self-deposit create is blocked until #368 is fixed.
