### ISSUE TITLE
Update 'Publish' for single repo environment

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#334]
**FROM SOW**
INFA-1
3.	Update “Publish” functionality to copy current draft:xxx.yyy.zzz to tufts:xxx.yyy.zzz and update edited and published dates on draft  and published objects appropriately, log the action

- [x] move publish! method into DraftVersion module
- [x] make push_to_production! a private method, update failing specs
- [x] update pids accordingly with PidUtils class
- [x] ensure that published_at and edited_at are updated appropriately
- [x] ensure published? on draft objects reports correctly

**Comment by tonyc** [comment]
PublishService.publish(obj)

**Comment by tonyc** [comment]
Double checking the last couple items here... I may have just forgotten to check the checkboxes :)
