### ISSUE TITLE
Add visual indication of object status in search views

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#335]
INFRA-1
4.	In the catalog index view, add visual indication of object status
    a.	Draft only => published_at = nil , edited_at != nil
    b.	Published => published_at != nil, edited_at != nil
    c.	Published with unpublished edits => published_at < edited_at

**NOTE** published? currently returns false for pending edits

![mira-335 publication status - search view](https://cloud.githubusercontent.com/assets/3064318/7152639/4a4263d2-e305-11e4-95d1-b2bcfdd770a6.png)

**Comment by mark-dce** [comment]
The current icons and color coding aren't set in stone.  Justin has proposed color coded text for unpublished and pending edits items rather than an icon.  The simplest (& most flexible?) solution might be to provide a css span and sample css classes that could be updated by Tufts.

**Comment by tonyc** [comment]
Blocked by #396
