### ISSUE TITLE
Add visual indication of object status in single item view

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#336]
INFRA-1
5.	In single item views, add visual indication of object status
a.	Draft only
b.	Published
c.	Published with unpublished edits

![mira-336 publication status - item view](https://cloud.githubusercontent.com/assets/3064318/7152716/a3e87d8a-e306-11e4-9b07-3fe5c95e43b9.png)

**Comment by mark-dce** [comment]
visual indication = something beyond a label in a single color.
Consider label in color + glyphicon

**Comment by mark-dce** [comment]
Consider just providing a css span and sample css that can later be edited by Tufts.

**Comment by tonyc** [comment]
Blocked by #396
