### ISSUE TITLE
Add "Revert" capability

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#337]
INFRA-1
6.	“Revert” an edited published object - copy the published copy over the draft copy, log the action

**Comment by tonyc** [comment]
Note BaseModel.revert_to_production!

This implementation needs to be changed. We should probably kill this method and name it similarly to the other workflow methods, e.g. "revert!"

**Comment by acozine** [comment]
I edited an object and have not published it: http://devmira.curationexperts.com/catalog/draft:MS036.011.DO.00001 - it shows as "edited" but I don't see a "Revert Edits" link on the page.  Can you add a link?

**Comment by tonyc** [comment]
re-test
