### ISSUE TITLE
Update "Purge" capability

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#339]
INFRA-1
8.	“Purge” an object - hard delete both draft and published copies (if existing), log administrative user, timestamp, and link to file content on the bucket server

**Comment by mark-dce** [comment]
Purges need to be tracked in some way for auditablity

**Comment by jcoyne** [comment]
It still seems to be using soft-delete (object_status: 'D')

**Comment by jcoyne** [comment]
However, I don't see any code that actually sets that.

**Comment by jcoyne** [comment]
Here's the offending code: https://github.com/curationexperts/mira/blob/master/app/controllers/records_controller.rb#L85-L86
