### ISSUE TITLE
Batch Review

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#345]
INFRA-1
9.	Provide batch support for
f.	Review

- [ ] Batch show view

**Comment by mark-dce** [comment]
Basically assumed to be regression testing the current Batch review on single items and batches.

**Comment by acozine** [comment]
Confirmed that this still works as follows:
You can review any individual item by opening its show view and clicking on Mark as Reviewed in the Tools list.
To review a batch of items, open the batch view, click on Review Batch. This takes you to a search results page with the items in the batch:
http://devmira.curationexperts.com/catalog?q=30&search_field=batch
To change the Review Status, open the first object's show view and click on the Mark as Reviewed link in the Tools section. You can then use the Previous and Next links to review each object in the batch in turn. 
The Review Status checkbox is visible in the Unpublished Items list, and you can review items from there as well.
