### ISSUE TITLE
Validate Checksumming

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#347]
INFRA-1
10.	Ensure that valid checksums are generated for new objects, metadata updates, and changes to file attachments.
a.	Determine whether external file attachments checksum reflects url or actual content
b.	Trigger checksum recalculation when attaching updated file datastreams

**Comment by mark-dce** [comment]
Notes from #322
See http://fedora-commons.1317035.n2.nabble.com/modifyDatastreamByValue-checksum-mismatch-td3979988.html

Test whether nulling the file datastream checksum on publish fixes this issue.

**Comment by jcoyne** [comment]
No checksums are generated. Do we have the correct fedora config? https://github.com/curationexperts/mira/blob/master/fedora_conf/conf/development/fedora.fcfg#L231

**Comment by jcoyne** [comment]
In answer to the question, we should turn the auto-checksumming on in fedora.fcfg

**Comment by jcoyne** [comment]
Once turning the checksum on, I get a "WARN 2015-04-27 13:16:06.340 [btpool0-7] (Datastream) IOException reading datastream to generate checksum" I suspect that Fedora is reading the dsLocation copy here: http://bucket01.lib.tufts.edu/data01/tufts/sas/archival_tif/5.archival.tif

Since that is not a resolvable URL, we can't duplicate the problem.

**Comment by jcoyne** [comment]
I expect this will also be a problem with the RELS-EXT datastream, because it's actually mutated.

**Comment by jcoyne** [comment]
It is possible to strip out the checksums, but then they are not recalculated on import.

**Comment by mark-dce** [comment]
@jcoyne - I'm not sure I understand your comments well enough to understand how we've satisfied the requirements of the SOW.

If Tufts need to convert http://bucket01.lib.tufts.edu/data01/tufts/sas/archival_tif/5.archival.tif to a valid file:// reference for checksums to work, then we need to communicate this requirement to them.

NOTE: In anticipation of this issue, we have identified the following as a "Tufts responsibility": Update all existing objects to have valid bucket pointer settings for external files.  But we need to tell them that this really needs to happen.  Alternatives would include updating the code to explicitly turn off checksumming for specific data streams.

**Comment by jcoyne** [comment]
I don't think we have yet. My code simply stripped the checksums out so the error was not encountered.

**Comment by jcoyne** [comment]
Blocked by #580

**Comment by mark-dce** [comment]
I'm pretty sure we can skip setting up the bucket  server and setting the trim_bucket_url in the application.yml as shown in the example below.  I.E. set the trim bucket url to a file resolver pointing at the same directory as the object_store_root.

```yaml
# config/application.yml
defaults:
# ...defaults omitted...
# ...other sections omitted...
production:
  <<: *defaults
#  derivatives_failure_address: "alicia@curationexperts.com"
  tdl_feedback_address: "alicia@curationexperts.com"
  object_store_root: "/demo/bucket"
  object_store_base: "data01/tufts"
  trim_bucket_url: "file:///demo/bucket"
#  handle_namespace: 10427.TEST
  handle_prefix: 10427.TEST
  handle_private_key:   /hs/srv_2/admpriv.bin2
  handle_batch_tool:    /hs/hsj-7.3.1/bin/hdl-genericbatch
  handle_email:         brian.goodmon@tufts.edu
  handle_admin:         0.NA/10427.TEST
# mike's settings
#  object_store_root: "/demo"
#  object_store_base: '/'
#  object_store_dca: 'remote05'
#  object_store_tisch: 'ase_remote'
# restore this one for sure
#  trim_bucket_url: "http://bucket01.curationexperts.com"
  processing_url: "http://127.0.0.1:8080"
  repository_url: "http://127.0.0.1:8080"

**Comment by acozine** [comment]
I changed the trim_bucket_url on devmira (in the production section, not in the defaults as shown above) to point to "file:///demo/bucket", then uploaded an image. The devmira fedora appears to be adding checksums:  http://devmira.curationexperts.com:8080/fedora/objects/draft:109/datastreams/Archival.tif
Checksum on the draft is 20414a71b66605acb1486562e8969425. I published the object, and the checksum is there in the tufts namespace: http://devmira.curationexperts.com:8080/fedora/objects/tufts:109/datastreams/Archival.tif .

**Comment by mark-dce** [comment]
Looks good - you can see all the datastream checksums on the foxml display ("xml represetation of this object"): http://devmira.curationexperts.com:8080/fedora/objects/draft:109/objectXML

Now that we can see checksums being generated, I'm going to close this ticket and open specific tickets for the issues that are appearing.
