### ISSUE TITLE
Separate administrative logging

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#354]
INFRA-1
13.	Separate out administrative logging to an independent log file (separate from the rails log) that can have a different retention policy

**Comment by mark-dce** [comment]
Team should have a discussion about whether to meet this requirement via a log file or fixing audit logging on an individual object level.

The solution needs to provide some type of audit-ability for purged and deleted objects.

**Comment by jcoyne** [comment]
Apparently the existing logging was working correctly, it only contains the most recent audit item, but the datastream is versionable, so you can look through the versions to get the history.

**Comment by acozine** [comment]
Administrative actions now get logged in log/audit.log instead of in Fedora. This should lead to faster performance as well as easier tracking.
