### ISSUE TITLE
Script to copy template config files

### ISSUE THREAD

**Issue by tonyc** [curationexperts/mira#360]
Write a shell script or rake task to copy any templated/sample files in config/ to their correct name.

Automating this step saves time during setup and any time the configs need to be copied over.

**Comment by val99erie** [comment]
It would be nice if the task also generated new secret key(s) for you and inserted them into the correct files, config/initializers/secret_token.rb and config/devise.yml.  (Assuming that devise.yml is still needed)

**Comment by tonyc** [comment]
Closing, since this has been completed (lib/tasks/config.rake)
