### ISSUE TITLE
Refactor code to remove references to data_stage and data_production

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#361]
As much as possible, remove the legacy references to having two fedoras (data_stage and data_prod) and make this look like a vanilla hydra application with a single fedora.

e.g. see config/initializers/active_fedora_override.rb

it doesn't seem like this is typical hydra code.

**Comment by tonyc** [comment]
* Remove ```#production_fedora_connection``` in ```app/models/concerns/publishable.rb```
* Remove references to ```:prod``` and ```ActiveFedora.data_production_credentials``` in ```spec/job/revert_spec.rb```
* Remove ```data_production_credentials``` from ```lib/active_fedora_override.rb```
