### ISSUE TITLE
Fix login link on default page

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/MIRA#38]
When I visit `/` and am redirected to `/contribute` the login link is currently broken.

See the login change here (and possibly revert it) https://github.com/curationexperts/MIRA/commit/df946e2cd87a80a1040b49002593fb3548a9e476#diff-fefbc2665b80a587c3b1cf5b202fd984L22

**Comment by no-reply** [comment]
Closed by #46.

@little9: if you include `Closes #X` in the PR comment/commit message, rather than the title, the corresponding issues will close on merge.
