### ISSUE TITLE
Add download links to single item view

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#381]
MIRA-1
4.	Single Item View - allow download of all datastreams (see AudioText for reference UI)
- [x] a.	Add download links for video content & transcripts (when present) for TuftsVideo objects
- [ ] b.	Add download link for transfer copy for TuftsPdf objects
- [ ] c.	Add download links for all available attachments for GenericObject objects
- [ ] d.	All download links should follow the pattern “download datastream_name” (change text on existing PDF download link; check other existing links & change as necessary)

**Comment by mark-dce** [comment]
Split out 4c into separate ticket

**Comment by mark-dce** [comment]
For each object type make sure that the there is a download link for each datastream

**Comment by jcoyne** [comment]
Is there any specific authorization needed?  Must be an admin?

**Comment by mark-dce** [comment]
**SUMMARY**
If I'm not logged in, I already get prompted to log in if I try to access a link like http://devmira.curationexperts.com/downloads/draft:MS025.006.004.00003.00001?datastream_id=ARCHIVAL_WAV

**LONGER DISCUSSION**
You can only log in to MIRA as an admin, so technically yes.  You can't get to the show page unless your logged in as an admin.  So, I guess it's a question of whether we're worried that an admin might copy a link to a download and send it to someone that shouldn't be authorized.  

If it's easy to add the admin authorization, that's probably most correct.  But if I'm an admin I can download the file and send it to someone anyway so protecting the download link doesn't provide significant additional content protection.

**Comment by val99erie** [comment]
@mark-dce Is there already a ticket for 4c?

**Comment by mark-dce** [comment]
See #517 for 4c

**Comment by mark-dce** [comment]
Refined in #515
