### ISSUE TITLE
Create handles on "Publish"

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#385]
MIRA-2
3.	Create a handle when an object is published to DL if one does not already exist
a.	When an object is published and set to display in “DL”, and doesn’t already have a handle, then run a background job that registers a handle and adds the handle to the object metadata  
b.	Publish the object immediately; add the handle metadata to both draft and published versions of the object when the handle job succeeds

**Comment by val99erie** [comment]
We need to be careful about how we update objects after publish.  Currently we are using date comparison to determine whether or not an object is published, so we need to be aware of that.  Make sure the object still correctly reports itself as published or not.
