### ISSUE TITLE
Restore the admin menu

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/MIRA#39]
When an administrator logs in, they should see the admin landing page.
<img width="832" alt="mira-39 admin landing page" src="https://user-images.githubusercontent.com/3064318/27336115-39526942-5594-11e7-82f3-af95f58e3629.png">

**Comment by no-reply** [comment]
The hyrax `catalog/index.html.erb` template doesn't show the `_home_text` template. I think we should restore the default blacklight index by including it directly in the MIRA catalog views.

When I do this, I get some errors from the admin page that I'm resolving now. The branch is [feature/admin_home](https://github.com/curationexperts/MIRA/tree/feature/admin_home).
