### ISSUE TITLE
Provide metadata download link on batch status page

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#392]
MIRA-3 
4.	Allow batch exports to be downloaded from the “Batch Status” page

* Each PID should list status similar to other batch jobs:
     * Queued
     * Working
     * Completed 
     * Error
* Overall job status
    * Queued/Working
    * Completed (all metadata exported successfully)
    * Errors (one or more objects has an issue, export file contains successfully exported PIDs)
* Export 
    * Button disabled until job is complete (Completed or Errors)
    * Links to download XML file

![mira-392 batch export - status](https://cloud.githubusercontent.com/assets/3064318/7161381/5ac87580-e354-11e4-908d-b03e1ece2fa1.png)

![mira-392 batch export - download](https://cloud.githubusercontent.com/assets/3064318/7161416/949a39ba-e354-11e4-9bbf-65a06a14a6fa.png)

**Comment by tonyc** [comment]
Link should appear after PIDs have been exported per #389
