### ISSUE TITLE
Update Import Functions to work against FC4/Hyrax

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/MIRA#4]

**Comment by no-reply** [comment]
Depends on #2

**Comment by no-reply** [comment]
This is for import of objects generated outside of Fedora. In Fedora 3, this is a FOXML light import; what is the import format for these for Fedora 4?

We should work up an initial proposal for discussion with Tufts.

**Comment by mark-dce** [comment]
Moved to epigaea repo
