### ISSUE TITLE
Remove user creation and tests

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/MIRA#41]
Since we're basing the authentication on the institution's LDAP, we should not longer support self registration.

**ACCEPTANCE**
- [ ] Sign-up features are removed from the application

**NOTES**
https://github.com/curationexperts/MIRA/blob/develop/spec/features/user_sign_up_spec.rb

https://github.com/curationexperts/MIRA/blob/develop/app/views/_user_util_links.html.erb#L4

**Comment by little9** [comment]
Removing the link is addressed in issue #47 .
