### ISSUE TITLE
Batches should persist over deployments

### ISSUE THREAD

**Issue by acozine** [curationexperts/mira#441]
For xml imports, the details are stored in the uploads/ folder. That folder is not currently shared, so each redeploy makes the batch files inaccessible. Not sure of the best solution for testing, or for production use. Share the folder in capistrano? Make the batches themselves purge-able?

**Comment by acozine** [comment]
For testing purposes, it's possible to remove all batches from the console with `Batch.delete_all`

**Comment by mark-dce** [comment]
After discussion, team agreed shared folder solution was probably best.
