### ISSUE TITLE
Fix css on batch update confirm page

### ISSUE THREAD

**Issue by acozine** [curationexperts/mira#444]
To reach the page, search for items, select at least one, and click on Apply Template. The next screen asks you whether you want to Preserve or Overwrite existing metadata when you apply the template.
Currently looks like this:

![screen shot 2015-05-05 at 3 17 36 pm](https://cloud.githubusercontent.com/assets/879121/7481986/ebf61964-f339-11e4-9b65-39e2f83ac83b.png)
Related to #310

**Comment by jcoyne** [comment]
This is BatchTemplateUpdate#ew
