### ISSUE TITLE
Single-item create for GenericObject

### ISSUE THREAD

**Issue by tonyc** [curationexperts/mira#446]
Update the single-item create pages in MIRA for TuftsGenericObject to allow optional additional datastreams (any number, any type of binary files) and generation of appropriate manifest

**Comment by mark-dce** [comment]
Looks like we can do both things:
- [x] allow optional additional datastreams (any number, any type of binary files) 
- [x] generation of appropriate manifest

We'll add a new ticket later for "upload generic file attachments" if Tufts feels that's necessary and we can find other scope to exchange for that work.
