### ISSUE TITLE
"View in Fedora" link error

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#458]
When I click on the "View in Fedora" link on an object on mira. or devmira. I get a link something like http://hydraadmin-dev.uit.tufts.edu:8080/pid

**NOTES:** It looks like we need to edit the application.yml file and open port 8080

**ACCEPTANCE**
- [x] When I click on the "View in Fedora" link, I see the object summary for the PID in fedora

**Comment by mark-dce** [comment]
I just checked again to see if the routing policies had taken effect.  I still can't access fedora remotely.  

On **devmira** console via ssh:
*works:* curl http://localhost:8080/fedora/objects/tufts:34
*fails:* curl http://107.22.178.68:8080/fedora/objects/tufts:34
*fails:* curl http://devmira.curationexperts.com:8080/fedora/objects/tufts:34
*fails:* access from remote browser 

Turning off the firewall temporarily with `sudo service iptables stop` allows me to access fedora from a remote browser, so it looks like we just need to make a permanent IPTables entry:

`-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT `

I added this line just after the port 80 config to the /etc/sysconfig/iptables file on mira.curationexperts.com and devmira.curationexperts.com.

**Comment by mark-dce** [comment]
Alicia - can you check the above and make sure it seems reasonable?  Do we need to do anything else to persist the iptables changes?  If not, go ahead and close this ticket.

**Comment by mark-dce** [comment]
@acozine - FYI, it doesn't look like vim is installed on mira.curationexperts.com, but it is installed on dev-mira.

**Comment by acozine** [comment]
EC2 security group settings and iptables settings are now working together correctly and should survive a reboot - thanks @mark-dce for the final piece.
