### ISSUE TITLE
Do not display production pids in MIRA index results

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#467]
**STORY**
As an admin, I only want to see the editable (draft) version of the object, so that I don't have to figure out which copy I need to operate on.

**DETAILS**
Since you can only edit the draft version and publish, unpublish, purge, revert all impact both copies, there's really no need to show a second (published) copy of the object

**ACCEPTANCE**
- [x] only the draft:xxx version of an object shows up in MIRA search results for the catalog controller
- [x] only the draft:xxx version shows up in the "unpublished" list

**Comment by jcoyne** [comment]
I believe that all templates are in the "tufts" namespace, so this may get tricky.

**Comment by val99erie** [comment]
@jcoyne The templates are already excluded from the catalog index - they have their own controller - so it shouldn't be a problem

**Comment by val99erie** [comment]
Also, advanced search page
