### ISSUE TITLE
Batch XML ingest fails to read xml file

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#474]
**STEPS TO REPRODUCE**
Using sample data from google drive: [DCE Clients/Tufts/2014-03 - Digital Image Head/Sample Data/XML Import/elephant-n-castle](https://drive.google.com/a/curationexperts.com/folderview?id=0BytolfRBVL3rcE1IajJISWVJNWs&usp=sharing)
1) Select the xml import file: tripletest.xml
2) Click "next"
3) Get a nondescript error

Production log shows no errors
Import worked successfully as of 83febffc53314e7934c11850547dec7aab0dcc40 
Fails with current commit 0739994b82e31e7e4cc2d0eb0eb106ef750e9508

**Comment by mark-dce** [comment]
$ git bisect bad
9119212d449e435ff0df7404d8fdb806ba646235 is the first bad commit
commit 9119212d449e435ff0df7404d8fdb806ba646235
Author: Justin Coyne <justin@curationexperts.com>
Date:   Fri May 1 17:33:43 2015 -0500

    extract BatchXmlImport actions into its own controller
    The BatchController was becoming unwieldly.
    This supports work on #378

:040000 040000 3ca1798861afcdc20c6bc9581ebf3e22430ac755 ec64569231562dbd6a545c99c6624a65bcc3f0fb M	app
:040000 040000 38b5ee6a52713efd0a47875fb2cd81598eec8f03 7e81906742ec4ed35fb8133462cf01aa262bf0be M	config
:040000 040000 eecd3987f88da7ee4842c22d7d77e34d7c358536 5d758a03001b22899719f84551c20d53f52aac15 M	spec

**Comment by jcoyne** [comment]
Where can I find `elephant-n-castle/tripletes.xml`?
