### ISSUE TITLE
Give hint text in the first displays option in the metadata editor

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#476]
**STORY**
As a metadata administrator, I would like the first item in the displays list to be non-selectable with text that says 'Choose option', so that the error message I get is clearer.

**DETAILS**
Currently if I leave the field at it's default, I get an error that says "*Displays in portal" / "must be in list" - when what the application really needs is for at least one valid display entry to be included.

This could be fixed by changing the error messaging or the box default or the behavior on blank items.

Maybe the validator needs to be fixed?

**ACCEPTANCE**
- [x] A) Ignore blank input fields
- [x] B) If there are no entries, give an error that at least on valid displays must be selected
- [x] C) Add hint text in field
- [x] D) **BONUS** if the same display term is listed twice, de-duplicate the list before saving
- [ ] E) **DOUBLE-PLUS BONUS** refactor the UI as checkboxes

**MOCKUPS**
A) Ignore blank input fields - currently gives the error below, should just ignore the fifth entry in the list
![mira-476 a ignore blank displays entries](https://cloud.githubusercontent.com/assets/3064318/7840637/f4574850-045d-11e5-8826-051e3663b979.png)

B) If there are no entries, give an error that at least on valid displays must be selected
![mira-476 b give better displays validation error](https://cloud.githubusercontent.com/assets/3064318/7840744/75da2f3c-045e-11e5-8d8b-d888291d1f59.png)

C) Add hint text in field
![mira-476 c give input hint](https://cloud.githubusercontent.com/assets/3064318/7841066/e6d4ef64-045f-11e5-8c45-7f1258262979.png)

D) **BONUS** if the same display term is listed twice, de-duplicate the list before saving
![mira-476 d de-duplicate values](https://cloud.githubusercontent.com/assets/3064318/7841172/6ac9eb44-0460-11e5-99ae-945fea834177.png)

E) Show each valid option next to a checkbox; if the object has values in the field that do not exist in the authority show them as greyed out, struck through, and unchecked *no wireframe at this time since it sounds like the editor couldn't handle this*

**Comment by jcoyne** [comment]
Is this still an issue with the new create screen?

**Comment by mark-dce** [comment]
It's an issue in the metadata editor for pre-existing objects, especially if you've modified the displays.yml options.
