### ISSUE TITLE
MIME-type warning on XML upload of audio files

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#487]
**ISSUE**
When I attempt to do an XML import of a wave file, I get a mime-type warning.  I don't get this warning if I use the same .wav file to create an object manually (via the "Create new object" main menu option).  I should be able to upload WAV or MP3 files as the archival master audio.

Confirmed issue in Safari 7.1.6, Chrome 43.0.2357.81, Firefox 38.0.1

**SAMPLE FILES**
on google drive [2015-03 MIRA Enhancements Implementation/Sample Data/](https://drive.google.com/a/curationexperts.com/folderview?id=0BytolfRBVL3rbzFvOE4xUjFwWlE&usp=sharing)
XML Import/[Tufts Samples A.xml](https://drive.google.com/a/curationexperts.com/file/d/0BytolfRBVL3rS1RyR3lQaFdmeHc/view?usp=sharing)
Sample Objects from Tufts/data_files/[MS025.006.004.00003.00001.archival.wav](https://drive.google.com/a/curationexperts.com/file/d/0B_Lst356jNA0Mmd1YnhjV2FQVTg/view?usp=sharing)
Sample Objects from Tufts/data_files/[MS122.002.001.00142.archival.mp3](https://drive.google.com/open?id=0B_Lst356jNA0Nlg5QjJ2ck9pUnM&authuser=0)

**SCREEN SHOT**
![mira-487 xml import mime-type warning](https://cloud.githubusercontent.com/assets/3064318/7849631/082499c0-049d-11e5-9275-cdc511f39347.png)

**Comment by jcoyne** [comment]
This is because your system is not sending the correct mime type for tei files. What application created the TEI for you? It should have a mime type of application/xml+tei.  You can edit your system associations for files using http://www.rubicode.com/Software/RCDefaultApp/
