### ISSUE TITLE
Invalid file-type warning when trying to upload TEI encoded transcripts

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#489]
**ISSUE**
When I attempt to attach a TEI encoded transcript with a .tei extension to a video object, I get a warning message that the file is the wrong type.  The system goes ahead and attaches the file, but does not recognize it as an XML mime type.

Confirmed issue in Safari 7.1.6, Chrome 43.0.2357.81, Firefox 38.0.1

**SAMPLE FILES**
on google drive [2015-03 MIRA Enhancements Implementation/Sample Data/](https://drive.google.com/a/curationexperts.com/folderview?id=0BytolfRBVL3rbzFvOE4xUjFwWlE&usp=sharing)
Sample Objects from Tufts/data_files/[UA236.001.001.00001.archival.tei](https://drive.google.com/a/curationexperts.com/file/d/0B_Lst356jNA0R2ZSbTdtQXZ1TFk/view?usp=sharing)
Sample Objects from Tufts/data_files/[UA236.001.001.00001.archival.tei copy.xml](https://drive.google.com/a/curationexperts.com/file/d/0BytolfRBVL3rWEhOTlJxYWtxcEU/view?usp=sharing)

**STEPS TO REPRODUCE**
1) Create a new video object (or manage data streams on an existing video)
2) Attach the .tei sample file - you get the error
3) Attach the ...tei copy.xml version - no error
The two files are identical copies, one just has a different extension added

**ACCEPTANCE**
Tufts probably has a number of existing transcripts with the .tei extension.  (2 of the 3 sample transcripts they provided have xml rather than tie extensions.)  It would be preferable if the system could recognize .tei extensions as a text/xml mime type (or inspect the actual file contents); otherwise, we will have to notify Tufts that they will need to ensure all of their transcripts have a .xml extension.  

**SCREEN SHOT**
![mira-489 transcipt attachment gives error on tei files](https://cloud.githubusercontent.com/assets/3064318/7850342/83d54f2a-04a6-11e5-9d87-4093036779e4.png)

**Comment by jcoyne** [comment]
This is because your browser is not configured to know about tei files. There ought to be a way to configure it to associate *.tei with application/xml+tei, then it will send the correct mime type to the server.  How did you get this file on your system in the first place?

**Comment by jcoyne** [comment]
Whatever application created this file should have tei specified in it's `Contents/Info.plist` file:

```xml
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>tei</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>MacVim-xml</string>
                       <key>CFBundleTypeMIMETypes</key>
                       <array>
                                 <string>text/xml</string>
                       </array>
			<key>CFBundleTypeName</key>
			<string>TEI File</string>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSIsAppleDefaultForType</key>
			<true/>
		</dict>
```

**Comment by mark-dce** [comment]
@mark-dce to see if I can register .tei with appropriate mime-type on my local machine.

**Comment by mark-dce** [comment]
So when I check the mime type on the local files system it looks correct:
```bash
MARKs-MB-2:data_files mark$ file --mime MS165.002.001.00006.archival.tei
MS165.002.001.00006.archival.tei: application/xml; charset=us-ascii
MARKs-MB-2:data_files mark$ file --mime UA236.001.001.00001.archival.tei
UA236.001.001.00001.archival.tei: application/xml; charset=us-ascii
MARKs-MB-2:data_files mark$ 
```

**Comment by mark-dce** [comment]
Spent 1.5+ hours trying to hack the mime-type Safari supplies and failed :(

Tufts has not reported this as an issue uploading any TEI files, so possibly the issue doesn't occur on Windows platforms in the same way.  For now, we'll call out the issue for Tufts to test (and just append .xml to the import files for our testing)
