### ISSUE TITLE
Should be able to reserve handle for an unpublished item

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#496]
**ISSUE**
Using the command-line rake task to register handles, I can't reserve a handle for an object before it's published.

(see MIRA-2 #2 - story #384)

**STEPS TO REPRODUCE**

1. Find or create an unpublished PID that does not have a handle assigned
2. Use the command line rake task to attempt to register a handle for the production version of the pid (see EXAMPLE below)
3. The rake task will report an error that it can't find the PID (this is partially true, there shouldn't be a production version of the PID at this point, but we should still be able to reserve a handle for it at this time). 

**NOTES**
* When I pass a draft pid to be registered, the production version of the pid should actually be the one that is registered.  There's no way for the general public (the primary consumers of the handle service) to resolve a handle registered to a draft:* pid
* The messaging should indicate that this is happening - i.e "Registering tufts:*** instead of draft:***" - see the Example below

**EXAMPLE**
```bash
[mark@ip-10-236-157-143 current]$ RAILS_ENV=production bundle exec rake handle:register[draft:MS115.003.001.00003.00001-a]
Registering a handle for draft:MS115.003.001.00003.00001-a
Batch(/opt/mira/releases/20150529144357/tmp/handle/handles-2015-05-29T15:19:53.103-8631.txt) process started ...
Batch process prints log on stdout ...
Batch process finished
Unable to find the object for draft:MS115.003.001.00003.00001-a
$
```

**Comment by jcoyne** [comment]
I think this is doing the right thing, I think the messaging is just wrong. Can you confirm?

**Comment by mark-dce** [comment]
How do I handle this case: I'm building draft:MS115.003.001.00003.00001-a but haven't published it to tufts:MS115.003.001.00003.00001-a yet but I want to go ahead an set up the handle (for whatever reason).

If I try the task with tufts:MS115.003.001.00003.00001-a as the parameter, I get the same error.

I
