### ISSUE TITLE
Handles not being generated on publication to DL

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#506]
**ISSUE**
When I publish an item, a handle isn't being generated the way it should.

**STEPS TO REPRODUCE**
(on devmira.curationexperts.com)

1. Create a new object, choosing 'dl' as the initial display
2. Find the new object in search results and view it
3. Publish the object
*EXPECTED RESULT:* The object should be published, a handle assigned, the handle is saved in the identifier term.
*ACTUAL RESULT:" No handle appears to be generated, nothing is saved as the identifier

**NOTE**
The handle should only be created if
1. The identifier is blank
2. The displays include 'dl'

**Comment by jcoyne** [comment]
```json
{"failed_at":"2015/05/29 14:49:55 UTC","payload":{"class":"Job::RegisterHandle","args":["4c413f45fe1dc9f1f1495900c1d7e588",{"record_id":"draft:mimetype.test"}]},"exception":"NoMethodError","error":"undefined method `id' for \"draft:mimetype.test\":String","backtrace":["/opt/mira/releases/20150529144357/app/services/register_handle_service.rb:93:in `url'","/opt/mira/releases/20150529144357/app/services/register_handle_service.rb:10:in `run'","/opt/mira/releases/20150529144357/lib/job/register_handle.rb:16:in `perform'","/opt/mira/shared/bundle/ruby/2.1.0/gems/resque-status-0.5.0/lib/resque/plugins/status.rb:161:in `safe_perform!'","/opt/mira/shared/bundle/ruby/2.1.0/gems/resque-status-0.5.0/lib/resque/plugins/status.rb:137:in `perform'"],"worker":"ip-10-236-157-143:7061:*","queue":"handle"}
```
