### ISSUE TITLE
Upload to devmira.curationexperts.com is *REALLY* slow

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#507]
**ISSUE**
I tried uploading a relatively small wav file to devmira and it took over 3 minutes.  The same file on my local development system takes under 3 seconds.  With that big of difference it doesn't just seem like an AWS bandwidth issue.  It also seems like uploading similar files when testing previously didn't take nearly as long.

Can we check the server and see if there are any file or memory issues or if there is anything else we can do to improve upload performance?

**Comment by mark-dce** [comment]
Seems happier now... (I did do a redeploy about 20 minutes ago)

**Comment by acozine** [comment]
Plenty of space on the box - /opt (where Solr and Fedora live) and /demo (where the external file datastreams live) are both at 25% used. Memory usage was higher, around 80%. I gave the box some swap memory to take care of peaks that max out the memory.
