### ISSUE TITLE
XML Import attaches file to random datastream

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#508]
**ISSUE**
If I don't specify the datastream a file should be attached to, the importer accepts any files and attaches them to a 'random' datastream.

**STEPS TO REPRODUCE**
1. Purge any copies of tufts:MS025.006.004.00003.00001 you already have in your repo
2. Use XML Import to import TC02
3. Select and upload a copy of MS025.006.004.00003.00001.archival.wav
*EXPECTED RESULT:* the audio gets attached to the ARCHIVAL_WAV datastream (or I get an error on Step 2 that the datastream wasn't specified)
*ACTUAL RESULT:* the audio gets attached the the ARCHIVAL_XML datastream - view the item and download the 'XML' to verify.  The WAV and MP3 attachments are both empty.

**NOTES**
It would be great if each object type has a default datastream if none is specified in the import file (as in TC02).  In the current state however, behavior seems to vary depending on whether the object already exists or not.  For comparison, you can try the import with TC01

TC01 - <file datastream='ARCHIVAL_WAV'>MS025.006.004.00003.00001.archival.wav</file>
TC02 - <file>MS025.006.004.00003.00001.archival.wav</file>

**SAMPLE DATA**
Use samples from google drive: https://drive.google.com/a/curationexperts.com/folderview?id=0BytolfRBVL3rbzFvOE4xUjFwWlE&usp=sharing
TC01 - Sample Data › XML Import › TC01 XML Multi-attach - single file.xml
TC02 - Sample Data › XML Import › TC02 XML Multi-attach - single file no datastream element.xml
WAV - Sample Data › Sample Content › MS025.006.004.00003.00001.archival.wav

**SCREENSHOT**
Note - this warning is probably because MIRA is attaching the WAV file to ARCHIVAL_XML
![mira-508 xml import gives erroneous mime type error](https://cloud.githubusercontent.com/assets/3064318/7892001/ce613880-0616-11e5-8b89-d15507e7e8f4.png)

**Comment by jcoyne** [comment]
If you don't supply a dsid, it is attaching it to the default datastream which is determined by:

```ruby
TuftsAudio.original_file_datastreams.first
=> "ARCHIVAL_XML"
```

**Comment by jcoyne** [comment]
Looks like the default datastream was changed in this commit: https://github.com/curationexperts/tufts_models/commit/552203fbc5af6b52ca3a74af34be7c78cd26b9a0#diff-03586a0874ec91ab7b90f1414084d441R173

We could make this more clear by moving the `default_datastream` method from `app/parsers/import_record.rb` to `Tufts::BaseModel` and adding tests for the expected values.

**Comment by jcoyne** [comment]
Also make sure to test TuftsVideo, it sufferes from the same problem:
```ruby
TuftsVideo.original_file_datastreams.first
 => "ARCHIVAL_XML"
```
