### ISSUE TITLE
"Internal Server Error" on XML Upload

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#518]
**ISSUE**
When I try to do an XML upload, after selecting and uploading content files, I get an internal server error.  I've replicated this in my development environment and on devmira.

**STEPS TO REPRODUCE**
1. Purge any copies of tufts:MS025.006.004.00003.00001 you already have in your repo
2. Use XML Import to import TC03
3. Select and upload a copy of MS025.006.004.00003.00001.archival.wav and MS025.006.004.00003.00001.archival.xml
*EXPECTED RESULT:* the files get imported and attached to the object without issues
*ACTUAL RESULT:* I get an "Internal Server Error" on the upload page (see screenshot), no object is created.

**SAMPLE DATA**
Use samples from google drive: https://drive.google.com/a/curationexperts.com/folderview?id=0BytolfRBVL3rbzFvOE4xUjFwWlE&usp=sharing
TC03 - Sample Data › XML Import › TTC03 XML Multi-attach - single object multiple datastreams.xml
WAV - Sample Data › Sample Content › MS025.006.004.00003.00001.archival.wav
XML - Sample Data › Sample Content › MS025.006.004.00003.00001.archival.XML

**SCREENSHOT**
![mira-518 xml upload internal server error](https://cloud.githubusercontent.com/assets/3064318/7921873/1e83a11e-086e-11e5-958b-f4e726e42756.png)

**Comment by jcoyne** [comment]
```ruby
NoMethodError (undefined method `compact' for nil:NilClass):
  app/actions/xml_batch_import_action.rb:17:in `run'
  app/controllers/batch/xml_imports_controller.rb:30:in `update'
```
