### ISSUE TITLE
Batch Status should only list each PID once for multi-file import

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#525]
**ISSUE**
On the batch status page, I see the same pid listed twice even though there was only one <digitalObject> in my import file.  I only imported the object once so I don't know why I'm seeing listed twice.

**NOTES**
The cleanest fix seems like it would be to just list each PID only once.  If that's overly complicated, we probably need to list the file that was attached so that multiple lines are unique and give the end-user some clue as to why the same PID shows up multiple times and why there are more detail lines than the total record count.

**SCREENSHOT**
![mira-525 pids repeated in batch status](https://cloud.githubusercontent.com/assets/3064318/7948151/87a68f42-0947-11e5-95e7-4d4066d0eccb.png)

**Comment by jcoyne** [comment]
@mark-dce The lines on the bottom are the status of the jobs spawned from this batch. Since there are two uploaded files (for the same pid) there are two lines.

**Comment by mark-dce** [comment]
@jcoyne - I'm still seeing this issue on the current commit of master.

**Comment by jcoyne** [comment]
@mark-dce but now it shows the filenames too, right? So you can now differentiate the multiple lines.

**Comment by mark-dce** [comment]
I missed that change, but it's probably sufficient.  I think, though,  we should somehow  keep the title for consistency with the other batch status pages.  I also could live with the new version, except it now has a record count of 2, and I only imported one digitalObject.  If you want to show a record count and a file count, that would be ok.  It's a little  confusing to show the file count (and call it record count)  in the place that is the "Fedora Objects Updated" count in every other batch status (that look identical).

**Comment by mark-dce** [comment]
So, could we update the view to show both the actual record count (1) and the file count (2).  I could live with that.
