### ISSUE TITLE
Add error on XML Import pre-processor if file node is blank

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#527]
```xml
<file datastream="ARCHIVAL_XML"></file>
```

Should give error text "Filename is missing" or something similar.

**Comment by jcoyne** [comment]
This is just like the export sample file. Are you sure?

**Comment by jcoyne** [comment]
This is for the XML object import.  If you do this you'll get a warning "Still missing filename {nil}"

**Comment by tonyc** [comment]
Error should happen during the validate step.

Check to make sure none of the file nodes have empty content.
