### ISSUE TITLE
Unspecified PID in xml import with multi-files fails

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#529]
**ISSUE**
When I leave the pid unspecified in an Archival Content Import, and I'm importing an object with multiple content data streams, I get multiple objects instead of a single object with multiple data streams.

**STEPS TO REPRODUCE**
1. Use Archival Content Import to import TC06
2. Select and upload a copy of MS025.006.004.00003.00001.archival.wav and MS025.006.004.00003.00001.archival.xml
*EXPECTED RESULT:* I get one new object with an auto generated pid that has both wav and xml files attached
*ACTUAL RESULT:* I get a separate pid for each file

**SAMPLE DATA**
Use samples from google drive: https://drive.google.com/a/curationexperts.com/folderview?id=0BytolfRBVL3rbzFvOE4xUjFwWlE&usp=sharing
TC06 - Sample Data › XML Import › TC06 Acrhival Import - autogenerate PID with multiple datastreams.xml
WAV - Sample Data › Sample Content › MS025.006.004.00003.00001.archival.wav
XML - Sample Data › Sample Content › MS025.006.004.00003.00001.archival.XML

**SCREENSHOT**
![mira-529 archival import - creates two objects when it should create one](https://cloud.githubusercontent.com/assets/3064318/7966421/96f99424-09e9-11e5-997d-888e2d2155e9.png)

**Comment by jcoyne** [comment]
Three potential solutions to this.

1) Forbid multi-file uploads from not having a pid
2) Take the SHA1 of the XML fragment for the object and make that the pid. The pid won't look the same as all the other pids.
3) Take the SHA1 of the XML fragment and make a lookup table in the database for hash to pid.  We'll need to be careful that the column holding the hash is unique and handle errors when a constraint violation is encountered.

**Comment by mark-dce** [comment]
It seems like objects that had enough care and attention to have multiple content files crafted for them, probably have enough care and attention that they'd get a pid assigned also.

Let's got with option 1) for now:  Add a validation that checks if multiple files are listed in a single <digitalObject> node and give an error like "a PID must be supplied for objects with multiple content data streams specified"

**Comment by mark-dce** [comment]
If there's only one <file> node within the <digitalObject>, keep the existing behavior and auto generate the pid.
