### ISSUE TITLE
Archival Content Import datastream defaults

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#535]
**ISSUE**
You can omit the datastream identifier when importing content files - see sample TC07.  Right now, the files get assigned to the 'default' data streams that you would expect, but I'm not sure if we have tests in place to ensure this behavior going forward.

**ACCEPTANCE**
- [ ] Either A or B
A) make sure we have tests that ensure <file> nodes without a datastream attribute get assigned to the right datastream
B) don't allow <file> nodes without a datastream attribute to be imported and give an error instead.

Option A is nicer because it's backwards compatible with the earlier specification for the XML import file.  But if it's alot more work, we should just do B

**DEFAULTS**
TuftsAudio: ARCHIVAL_WAV
TuftsEAD: Archival.xml
TuftsImage: Archival.tif
TuftsPdf: PDF_CONTENT_DS
TuftsRCR: RCR-CONTENT (xml)
TuftsTEI: Archival.xml
TuftsVideo: Archival.video (mp4)
TuftsVotingRecord: RECORD-XML

TuftsGenericObject: GENERIC-CONTENT *NOTE: this is a special case where the content does not get written directly to a file datastream*

**SAMPLE DATA**
Use samples from google drive: https://drive.google.com/a/curationexperts.com/folderview?id=0BytolfRBVL3rbzFvOE4xUjFwWlE&usp=sharing
TC07 - Sample Data › XML Import › TC07 Acrhival Import - mutiple file import with primary datastream IDs omitted.xml
WAV - Sample Data › Sample Content › MS025.006.004.00003.00001.archival.wav
XML - Sample Data › Sample Content › MS025.006.004.00003.00001.archival.XML

**Comment by jcoyne** [comment]
Done in https://github.com/curationexperts/tufts_models/commit/525ce65128b22d61c125664321af80fb3c86111a

**Comment by mark-dce** [comment]
Great - I sort of thought we had this covered, but wasn't sure.  Thanks for confirming.
