### ISSUE TITLE
RCR is a "Record Context Record" not "Collection Creator"

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#541]
For a definition of RCR see the "Purpose" section in http://sites.tufts.edu/dca/files/2011/03/DAT-040DCABestPracticesforEAC.pdf

Usages of "Collection Creator" should be refactored to "Record Context Record":
* https://github.com/curationexperts/mira/blob/master/config/locales/en.yml#L56
* https://github.com/curationexperts/mira/blob/master/spec/helpers/records_helper_spec.rb#L7
* https://github.com/curationexperts/mira/blob/master/spec/helpers/records_helper_spec.rb#L40

The two specs should probably be refactored to test the I18n.t values so we don't break code if someone changes the labels in the locale file.

**Comment by jcoyne** [comment]
https://github.com/curationexperts/mira/commit/c2ad6c52ab64b0750348c8c544260d7aae1351bb

It was added by @mkorcy, maybe he knows better than us.

**Comment by mkorcy** [comment]
@jcoyne whats the question?  They are RCRs but for display purposes DCA wanted the label to be Collection Creator as they thought the term was more approachable to end-users.  Was that the question?
