### ISSUE TITLE
Archival Content Import fails on PDF import

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#550]
**ISSUE**
When I try to do an Archival Import for PDF content, I get an "Internal Server Error" at the file upload page.

**STEPS TO REPRODUCE**
1.Use XML Import to import TC12
3. Select and upload a copy of Adelita.pdf and Adelita.sib
*EXPECTED RESULT:* the files get imported and attached to the object without issues
*ACTUAL RESULT:* I get an "Internal Server Error" on the upload page, no object is created.

**NOTE**
I was able to use the same sample content files to succesfully create a PDF object manually using the "Create a new object" link from the admin home page.

**SAMPLE DATA**
Use samples from google drive: https://drive.google.com/a/curationexperts.com/folderview?id=0BytolfRBVL3rbzFvOE4xUjFwWlE&usp=sharing
TC12 - Sample Data › XML Import › TC12 Archival Content Import - pdfs with sources.xml
PDF - Sample Data › *Sample Content from DCE* › Adelita.pdf 
Binary - Sample Data › *Sample Content from DCE* › Adelita.sib

**Comment by jcoyne** [comment]
```
NoMethodError (undefined method `dsLocation=' for nil:NilClass):
  app/services/archival_storage_service.rb:12:in `block in run'
  app/services/archival_storage_service.rb:11:in `tap'
  app/services/archival_storage_service.rb:11:in `run'
  app/actions/xml_batch_import_action.rb:51:in `create_file'
  app/actions/xml_batch_import_action.rb:28:in `block in create_model'
  app/actions/xml_batch_import_action.rb:27:in `each'
  app/actions/xml_batch_import_action.rb:27:in `create_model'
  app/actions/xml_batch_import_action.rb:11:in `block in run'
  app/actions/xml_batch_import_action.rb:10:in `each'
  app/actions/xml_batch_import_action.rb:10:in `run'
  app/controllers/batch/xml_imports_controller.rb:25:in `update'
```

**Comment by jcoyne** [comment]
The file on google drive has invalid datastream ids in it:
```xml
    <file datastream="PDF_CONTENT_DS">Adelita.pdf</file>
    <file datastream='TRANSFER_BINARY_DS'>Adelita.sib</file>
```

Those should be 'Archival.pdf' and 'Transfer.binary' respectively

**Comment by mark-dce** [comment]
Replaced by #556
