### ISSUE TITLE
Remove phantom download links after manage datastreams changes

### ISSUE THREAD

**Issue by acozine** [curationexperts/mira#554]
Steps to reproduce:
Create a multi-file object with more than one datastream (e.g. create an audio object with an audio file and a TEI transcript). The object show page has links to download both datastreams.
Open Manage Datastreams on that object, and delete the TEI transcript.
Return to the object show page. It will still have links to download both datastreams.
I should not see a link to download the transcript that is no longer there.

**Comment by val99erie** [comment]
I think the solr index isn't being updated when you remove a datastream
