### ISSUE TITLE
Create application.yml.sample

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#557]
Shouldn't this follow the pattern of all the other config files?  I.E. check an example file into github and then copy and localize it for your environment.

- [ ] move config/application.yml to config/application.yml.sample
- [ ] add config/application.yml to gitignore
- [ ] ensure rake config:copy task includes application.yml.sample

**Comment by tonyc** [comment]
If we decide to follow the pattern (we probably should), ensure it's also added to https://github.com/curationexperts/mira/blob/master/lib/tasks/config.rake

**Comment by jcoyne** [comment]
No, the only thing we should distribute .sample files for are those that contain sensitive information we don't want to put in github. So, that should really only be `secrets.yml` and `database.yml` (and devise.yml can be discarded with a current version of devise)

**Comment by acozine** [comment]
Yes, the main reason for .sample files is to avoid checking passwords into github for the world to see. However, they can serve another purpose - if we provide .sample files for all config files that need local changes, the person who deploys the software has an easy way to see which files need modification. As long as we provide the rake task and a functioning development section for each .sample file, I don't see a down-side. What do you think, @jcoyne?

**Comment by mark-dce** [comment]
Since Tufts wants to have two instances of MIRA running, one for Dark Archives, and one for Public Production, they will probably need differing application.yml on those two servers; otherwise only one config gets checked into github and always clobbers the other server.  It seems like the .sample pattern is a nice way to deal with this.

**Comment by mark-dce** [comment]
Hey - is the right answer to provide sample files only for things with passwords in them, and .gitignore the remaining configuration files, but explicitly check them in when we want to make updates?

**Comment by tonyc** [comment]
@mark-dce - I'm not sure that's exactly the right solution. IMO things in .gitignore shouldn't be checked in at all, and it's too easy to make a change to a file, intend to check it in, and then git entirely misses the fact that you changed it.

I generally agree with @jcoyne, but I'd also expand it from password/etc to "things likely to  change across environments/instances". I don't think there are many of these cases, but it seems application.yml is likely to change across instances.

If we do have a file that is likely to be changed across environments, then maybe we do actually need to do an application.yml.sample, and add the original to .gitignore.

**Comment by mark-dce** [comment]
Closing due to lack of consensus.
