### ISSUE TITLE
“Remember me” checkbox doesn’t work

### ISSUE THREAD

**Issue by pcantrell** [curationexperts/MIRA#56]
Attempt to log in as a valid user with “Remember me” checked. Fails with: `authenticatable_salt returned nil for the User model. In order to use rememberable, you must ensure a password is always set or have a remember_token column in your model or implement your own rememberable_value in the model with custom logic.`

**Comment by mkorcy** [comment]
We don't use remember me, feel free to disable.

**Comment by mkorcy** [comment]
Also based on previous title, in the devise initializer we use config.ldap_create_user to allow self depositors through.

**Comment by pcantrell** [comment]
Yeah, verified that new users get added to DB just fine after successful LDAP login as long as you don’t check “Remember me!”
