### ISSUE TITLE
Redirect or give nicer error message if you give a bad batch number

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#571]
**ISSUE**
Since we assign batch number sequentially regardless of type, we may have gaps in batch sequences for various types.

I'm tempted sometimes to look at the previous batch I worked on by just type a batch number in the address bar, which usually fails - i.e.

Batch 23 : http://localhost:3000/batch/template_imports/23
Batch 24: http://localhost:3000/batch/template_updates/24
Batch 25: http://localhost:3000/batch/publishes/25

So if I'm looking at batch 25 and want to look at the previous thing I did, I change 25-->24 in my address bar and get http://localhost:3000/batch/publishes/24 - which gives me either "ActiveRecord::RecordNotFound in Batch::PublishesController#show" in development or "We're sorry, something went wrong" in production.

In production, particularly, it would be good to provide a more specific error message like "Batch 24 was not a publication batch", or just redirect to the correct path for the batch type.

**Comment by jcoyne** [comment]
On production is should give you "The page you were looking for doesn't exist". That seems very reasonable error message. See http://devmira.curationexperts.com/batch/template_imports/23

**Comment by mark-dce** [comment]
@jcoyne Fair enough - I was assuming that was the "we're sorry something went wrong" message.
