### ISSUE TITLE
Enable checksums on MIRA and DEVMIRA

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#579]
**ISSUE**
In order to demonstrate we have met the requirements of INFRA 1-10, we need to show that the application runs successfully with checksumming enabled.

> **INFRA-1**
> 10)	Ensure that valid checksums are generated for new objects, metadata updates, and changes to file attachments.  
>    a.	Determine whether external file attachments checksum reflects url or actual content  
>    b.	Trigger checksum recalculation when attaching updated file datastreams

**NOTES**
Fedora documentation to enable checksums:  
https://wiki.duraspace.org/display/FEDORA38/Checksums

**ACCEPTANCE**
Should be enabled on
- [x] devmira.curationexperts.com
- [x] mira.cuartionexperts.com

**Comment by acozine** [comment]
See also #347 and #
