### ISSUE TITLE
Set up bucket server

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#580]
Needed to support testing for #347

Will need to change config application.yml accordingly.

**Comment by acozine** [comment]
Changed the application.yml on devmira to use the file: setting on devmira (as detailed in #347). Once we're sure this is the correct setup, I can update mira.curationexperts.com to match (fedora.fcfg and application.yml).

**Comment by acozine** [comment]
Based on #347, looks like this was the right setup. I've changed mira.curationexperts.com now as well.
