### ISSUE TITLE
Add single worker "manifest" queue to resque config.

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#582]
We need a queue dedicated to writing TuftsGenericObject manifests that only has a single worker.

This is necessary to support writing the GenericObject manifest without encountering concurrency issues or race conditions.

**Comment by acozine** [comment]
I've updated the resque-pool.yml files on devmira and mira - I looked through the code and included all the queues I could find. I commented out the "*" line so that all manifest jobs would be forced onto the same worker: 
```
production:
#  "*": 5
  "derivatives": 2
  "handle": 1
  "publish,unpublish,export,purge,revert": 2
  "templates": 1
  "manifest": 1
  "import": 1
```

**Comment by mark-dce** [comment]
It might be good to put a comment in after the 'manifest' entry:
```yaml
 "manifest": 1    #only allocate one worker to this queue to avoid concurrency related issues when writing TuftsGenericObject manifests
 ```

**Comment by acozine** [comment]
Per Mark's and Justin's suggestions, revised to:
```
production:
  "derivatives,handle,templates,import,publish,unpublish,export,purge,revert": 5
# all manifest jobs must be processed by a single worker
# to avoid concurrency issues
  "manifest": 1
```
