### ISSUE TITLE
Handle registration not logging errors to handle log

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#591]
**ISSUE**
When I try to register a handle and my handle config is invalid, I don't see any errors in the handle log, but I don't get a handle registration.

**ACCEPTANCE**
- [ ] I'd like to see the actual error in resque - it looks like we aren't properly passing the error text back from the handle server.  

- [x] I'd like something in the handle error log.

**DETAILS**
I have this failed job in resque:
```text
Worker
MARKs-MB-2.local:21180 on HANDLE at just now Retry or Remove
Class
 Job::RegisterHandle
Arguments
--- f72b78eba1918875f9bf919a9e1cee82
...

---
record_id: draft:001.002.003
Exception
Handle::HandleError
Error
Handle::HandleError
/Users/mark/.rvm/gems/ruby-2.1.2/gems/handle-system-0.0.7/lib/handle/command/connection.rb:86:in `create_handle'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/handle-system-0.0.7/lib/handle/command/persistence.rb:40:in `rescue in save'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/handle-system-0.0.7/lib/handle/command/persistence.rb:30:in `save'
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/mira/app/services/register_handle_service.rb:12:in `run'
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/mira/lib/job/register_handle.rb:17:in `perform'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/resque-status-0.5.0/lib/resque/plugins/status.rb:161:in `safe_perform!'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/resque-status-0.5.0/lib/resque/plugins/status.rb:137:in `perform'
```

If I try to register the PID in question from the command line, I get this error:
```bash
$ bundle exec rake handle:register[draft:001.002.003]
Registering a handle for draft:001.002.003
rake aborted!
Handle::HandleError: Invalid admin
/Users/mark/.rvm/gems/ruby-2.1.2/gems/handle-system-0.0.7/lib/handle/command/connection.rb:98:in `update_handle_values'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/handle-system-0.0.7/lib/handle/command/persistence.rb:36:in `block in save'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/handle-system-0.0.7/lib/handle/command/persistence.rb:34:in `each'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/handle-system-0.0.7/lib/handle/command/persistence.rb:34:in `save'
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/mira/app/services/register_handle_service.rb:12:in `run'
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/mira/lib/tasks/handle.rake:11:in `block (2 levels) in <top (required)>'
/Users/mark/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/mark/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => handle:register
(See full trace by running task with --trace)
```

![mira-591 handle errors not logging](https://cloud.githubusercontent.com/assets/3064318/8041972/f1b21e6e-0de9-11e5-8887-5293f23e8ddf.png)

**Comment by jcoyne** [comment]
Should it continue to raise an error, so that the error can be seen in resque web (see #509)

**Comment by jcoyne** [comment]
The handle gem that we are using does not have a way to "pass the actual error text" should we be forking that gem?

**Comment by mark-dce** [comment]
The SOW says:

> 4.	Log an error message for failed handle job: include object PID, timestamp, error returned by handle server
>    a.	Log handle errors to a separate handle log (i.e. do not log to admin log or main rails log)
>    b.	Provide a link to allow the handle error log to be viewed via browser by an authenticated administrator

I'm not sure how we meet that requirement otherwise.  We already demoed this to Tufts when we closed #386, so I fell like we're committed.

**Comment by mark-dce** [comment]
Would MBK be open to pull requests?  I still like the idea of a shared gem.

**Comment by jcoyne** [comment]
I wrote a pr 4 days ago that hasn't been reviewed yet. So, we probably wont get anything into that gem soon.

**Comment by mark-dce** [comment]
I'm now getting logging for certain types of errors, but not all.  So, I'm closing this ticket and opening tickets for the individual error cases.
