### ISSUE TITLE
Review Status shows "Incomplete" on Batch Status Page

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#593]
**ISSUE**
The Review Status still shows "Incomplete" on the Batch status page after I've marked all the items as reviewed.

**STEPS TO REPRODUCE**
1. Use XML Import to import TC03
2. Select and upload a copy of MS025.006.004.00003.00001.archival.wav and MS025.006.004.00003.00001.archival.xml
3. Click on the "Review Batch" button
4. Click on the first item in the list for review (This I believe)
5. Click on "Mark as Reviewed"
6. Go back to the batch status page for the batch
*EXPECTED RESULT:* All objects are marked as reviewed and "Review Status" is listed as complete
*ACTUAL RESULT:* Objects are marked as reviewed, but "Review Status" shows "Incomplete"

**SAMPLE DATA**
Use samples from google drive: https://drive.google.com/a/curationexperts.com/folderview?id=0BytolfRBVL3rbzFvOE4xUjFwWlE&usp=sharing
TC03 - Sample Data › XML Import › TTC03 XML Multi-attach - single object multiple datastreams.xml
WAV - Sample Data › Sample Content › MS025.006.004.00003.00001.archival.wav
XML - Sample Data › Sample Content › MS025.006.004.00003.00001.archival.XML

**SCREENSHOT**
![mira-593 batch status - review not showing complete](https://cloud.githubusercontent.com/assets/3064318/8042981/e8d66e88-0df0-11e5-98f4-b983b98d7021.png)

**Comment by jcoyne** [comment]
Screenshot is missing.
