### ISSUE TITLE
Publishing error

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/mira#615]
1) Create a new object
2) Select "Image," fill in a title and click "Next"
3) Click "Upload Archival.tiff", select a file and wait for it to upload
4)  Without clicking "Next," click "Upload Archival.tiff" again, and select the same file and wait for it to upload.
5) Click "Next"
6) On the edit page click "Save"
7) Click the "Publish link"
8) an Internal Server Error is raised.

**Comment by mark-dce** [comment]
I repeated the steps and got the same issue.   Here's the weird thing - if I upload a file and skip step 4, I get the same checksum for Archival.tiff, but different checksums for the thumbnail derivatives (and only the thumbnail)...

draft:122 - followed all steps - checksums: http://devmira.curationexperts.com:8080/fedora/objects/draft:122/objectXML

draft:121 - skipped step 4 - checksums: http://devmira.curationexperts.com:8080/fedora/objects/draft:121/objectXML

**Comment by jcoyne** [comment]
Seems like this is a variant of #609.

**Comment by mark-dce** [comment]
Yes - if I manually remove the thumbnail checksum just before the item gets copied, publish works fine - i.e. if I set a breakpoint here and edit `foxml`: https://github.com/curationexperts/mira/blob/master/app/services/fedora_object_copy_service.rb#L14

**Comment by jcoyne** [comment]
Closing as duplicate of #609
