### ISSUE TITLE
DCA-DETAIL-META not exported

### ISSUE THREAD

**Issue by e2d2** [curationexperts/mira#632]
The dca-detail-meta datastream is not included in metadata export file. See batch 128 where I tried to download all metadata for object draft:sd.0000104.

**Comment by tonyc** [comment]
Thanks for the report! It looks like the DS is actually called "DC-DETAIL-META" (not DCA-). This should be an easy fix from the GUI side to resolve.

**Comment by tonyc** [comment]
A similar problem also affects metadata import. This ticket will also resolve that, as well.
