### ISSUE TITLE
Publishing batch status says failed when publishing was actually successful.

### ISSUE THREAD

**Issue by e2d2** [curationexperts/mira#633]
I ingested two audio with transcripts using the xml - batch 130. Once I'd confirmed that both objects in the batch were ingested successfully, I clicked on "Publish Batch" from the batch 130 screen. The Publish batch became 131 which lists the status as failed even though both objects say that are successfully published.

**Comment by tonyc** [comment]
Rubydora::FedoraInvalidRequest

/opt/mira/shared/bundle/ruby/2.1.0/gems/rubydora-1.8.1/lib/rubydora/rest_api_client.rb:28:in `block (2 levels) in <module:RestApiClient>'
/opt/mira/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/rescuable.rb:114:in `instance_exec'
/opt/mira/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/rescuable.rb:114:in `block in handler_for_rescue'
/opt/mira/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/rescuable.rb:80:in `call'
/opt/mira/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/rescuable.rb:80:in `rescue_with_handler'
/opt/mira/shared/bundle/ruby/2.1.0/gems/rubydora-1.8.1/lib/rubydora/rest_api_client.rb:143:in `rescue in mint_pid_and_ingest'
/opt/mira/shared/bundle/ruby/2.1.0/gems/rubydora-1.8.1/lib/rubydora/rest_api_client.rb:136:in `mint_pid_and_ingest'
/opt/mira/shared/bundle/ruby/2.1.0/gems/rubydora-1.8.1/lib/rubydora/rest_api_client.rb:124:in `ingest'
/opt/mira/releases/20150617211747/app/services/fedora_object_copy_service.rb:14:in `run'
/opt/mira/releases/20150617211747/app/services/publish_service.rb:11:in `run'
/opt/mira/releases/20150617211747/lib/job/publish.rb:20:in `block in perform'
/opt/mira/releases/20150617211747/lib/job/run_as_batch_item.rb:10:in `run_as_batch_item'
/opt/mira/releases/20150617211747/lib/job/publish.rb:19:in `perform'
/opt/mira/shared/bundle/ruby/2.1.0/gems/resque-status-0.5.0/lib/resque/plugins/status.rb:161:in `safe_perform!'
/opt/mira/shared/bundle/ruby/2.1.0/gems/resque-status-0.5.0/lib/resque/plugins/status.rb:137:in `perform'

**Comment by tonyc** [comment]
@e2d2 - could you attach the original XML metadata file you used with this import? I've got the .wav and transcript .xml files.

Thanks!

**Comment by e2d2** [comment]
Here’s the metadata file for that ingest.

**Comment by tonyc** [comment]
@e2d2 - got it- thanks!

**Comment by tonyc** [comment]
This exception is occurring in Fedora after the file upload completes:

```
INFO 2015-06-18 19:13:07.370 [http-8080-8] (DefaultManagement) Completed modifyDatastreamByReference(pid: draft:MS025.006.001.00001.00001, datastreamId: DCA-ADMIN, altIDs: , dsLabel: ,
mimeType: text/xml, formatURI: null, dsLocation: uploaded://2211, checksumType: MD5, checksum: null, logMessage: null)
INFO 2015-06-18 19:13:07.371 [http-8080-8] (DefaultManagement) Completed getDatastream(pid: draft:MS025.006.001.00001.00001, datastreamID: DCA-ADMIN, asOfDateTime: null)
WARN 2015-06-18 19:13:08.344 [http-8080-8] (BaseRestResource) Resource not found: Object not found in low-level storage: tufts:MS025.006.001.00001.00001; unable to fulfill REST API requ
est
org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: Object not found in low-level storage: tufts:MS025.006.001.00001.00001
```

**Comment by tonyc** [comment]
Exception happening on https://github.com/curationexperts/mira/blob/master/app/services/fedora_object_copy_service.rb#L14

**Comment by mark-dce** [comment]
@tonyc - I just discovered that I can unreliably reproduce this issue by attempting to re-publish batch 130.

i.e. go here: http://mira.curationexperts.com/batch/xml_imports/130
and click publish - you'll sometimes get a new batch that shows all the individual items listed as completed and the overall status as failed:
http://mira.curationexperts.com/batch/publishes/146

I could only get this to happen once though so far...

Sorry - I was just about to close the ticket before this happened :{

**Comment by mark-dce** [comment]
I seem to be able to pretty consistently duplicate 633 (plus a variety of other error states) locally but setting up a batch with at least one pid repeated (preferably many times) and running multiple publish workers.  The more workers that are attempting to publish the pid at the same time the more likely you are to trigger the rubydora error.

I've also managed "ActiveFedora::ObjectNotFoundError", "RestClient::ResourceNotFound", along with "Rubydora::FedoraInvalidRequest"

There's definitely a disconnect on the batch show page between how the item-level status is determined and how the batch-level status is calculated.  Running with only one publish worker, I can get all items listed as completed with batch-level status as either 'Completed' or stuck at 'Working'.

Running multiple publish workers, I can get all items listed as completed with batch-level status that's either 'Completed' or 'Failed'
