### ISSUE TITLE
Fix RMagick deprecation warning

### ISSUE THREAD

**Issue by tonyc** [curationexperts/mira#636]
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead

Probably from https://github.com/curationexperts/tufts_models/blob/master/lib/tufts_models/engine.rb#L9

Check other locations i.e. Gemfile

**Comment by mark-dce** [comment]
Also

[DEPRECATION] `RSolr.escape` is deprecated (and incorrect).  Use `Rsolr.solr_escape` instead
> This appears to come from some dependency, can't find the reference in tufts_models

DEPRECATION WARNING: You attempted to set the attribute `title' on `TestObject' to an enumerable value. However, this attribute is declared as being singular. This behavior is deprecated and will raise an ArgumentError in active-fedora 8.0.0.
* title
* published_at
* edited_at
* createdby
* creatordept

**Comment by jcoyne** [comment]
Removing the RSolr.escape message requires upgrading to a new version of ActiveFedora.

**Comment by mark-dce** [comment]
We'll leave that for a future SOW.  For now I just fixed the RMagick --> rmagick require issue in tufts_models.
