### ISSUE TITLE
De-duplicate PIDs before accepting publish jobs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#645]
**ISSUE**
Publishing a batch import can result in pids being duplicated because each pid might have multiple files associated with it on import.

In a batch import job, the same pid is listed each time a unique file is associated with it.  If you publish the batch, you end can end up attempting to publish the same pid multiple times, which triggers contention issues - see #633

**Comment by tonyc** [comment]
De-duplicate for Publish, Unpublish, Purge, Revert
