### ISSUE TITLE
Problem with reverting unpublished to publish

### ISSUE THREAD

**Issue by amrri06** [curationexperts/mira#647]
It appears that the revert from unpublished to published isn't working on the display results page.
Here are the steps I performed:

Search all fields: margaret henderson floyd
System should retrieve 5 results
Click on draft:801 - Side of house framing Plymouth Plantation 
in the single item view click on unpublish.  The system gives you an unpublished status
click on MIRA
Repeat the search: margaret henderson floyd
draft:801 is unpublished
check box next to 1. Side of house framing Plymouth Plantation
click revert
system gives you a warning box - click OK
system displays batch status - refresh screen to see status complete
click on mira icon
search: margaret henderson floyd
draft:801 still says unpublished.

FYI - Reverting a published object to unpublish seems to be working.

Note:  If an item in the search results is unpublished and I select it I would expect that the box at the top of the page for unpublish would be greyed out.  that is, I wouldn't expect to be able to unpublish and unpublished item.  Same for other states (publish, revert)

**Comment by mark-dce** [comment]
@amrri06 - revert only reverts edits to an object back to their published status, it doesn't generically undo the last operation.

Per the SOW: 
Infra-1 #6.	“Revert” an edited published object - copy the published copy over the draft copy, log the action

**Comment by mark-dce** [comment]
FYI - In this case, you would just publish the object.
