### ISSUE TITLE
Trying to view a purged item in batch status

### ISSUE THREAD

**Issue by amrri06** [curationexperts/mira#648]
This may not really be an issue - just a feature, but I thought I'd mention it.

I purged a batch of images (batch id 153).  I clicked on batch id 153 and saw the list of 5 pids.  I then clicked on draft:792 and got the message "the page you were looking for doesn't exist"

I would have expected to see a message that said something like:  The object you are looking for was purged on 2015-06-19.

it may be that the message is a generic message and info about the object being purged is too specific, but I thought I'd mention it.

Alicia

**Comment by mark-dce** [comment]
@amrri06 - Since we're using hard deletes now, there's no longer a record in fedora corresponding to the pid, therefore, no way to distinguish between a pid that has been purged and one that never existed.
