### ISSUE TITLE
Replace raw metadata still results in "Sorry something went wrong" screen.

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/mira#651]
Did some significant cleanup on Batch export 181 limiting only to the DCA-META and the DC_DETAIL-META stream, and when I tried to re-import I got the "Sorry something went wrong" screen.  I'm sending the xml to Mark.

**Comment by mark-dce** [comment]
Confirmed after new code release - I'm still getting this error in the logs (testing on devmira with [this](https://drive.google.com/open?id=0BytolfRBVL3rX3BpOTVlOXJCdW8&authuser=0) import file)

```text
E, [2015-06-26T14:48:38.442477 #21251] ERROR -- : Mysql2::Error: Data too long for column 'metadata_file' at row 1: INSERT INTO `batches` (`created_at`, `creator_id`, `job_ids`, `metadata_file`, `pids`, `type`) VALUES ('2015-06-26 14:48:38', 6, '--- []\n', '<?xml version=\"1.0\" encoding=\"UTF-8\"?><items><digitalObject><pid>draft:208</pid><datastream id=\"DCA-META\">
```
