### ISSUE TITLE
displays authority doesn't extend to tufts_models

### ISSUE THREAD

**Issue by mkorcy** [curationexperts/mira#652]
@mark-dce in testing, I've swapped out the possible display heads available to mira, to some other set of heads: ["nowhere","corpora"]

Everything works as expected initially but when you actually set the displays of an object to corpora, the object fails the displays validation: "must include at least one valid entry"

Looking at tufts_models:

https://github.com/curationexperts/tufts_models/blob/f48fb53756d68beb2afa6d321a6985f62c8488df/app/models/concerns/with_valid_displays.rb

It appears this is still a static list, and so you can't configure mira to run with a different set of heads as expected.

**Comment by mark-dce** [comment]
So, the validations should probably take it's values from the YAML file, not be hard-coded
