### ISSUE TITLE
Fix LDAP config errors in MIRA

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/MIRA#77]
**ISSUE**
There isn't currently a valid configuration for LDAP in the test environment.

**NOTES** 
We probably need to copy over the ladel configuration that we're using to run the tufts_concerns test suite.  See https://github.com/curationexperts/tufts_concerns/commit/5d5b7ee2661e6b2f07fd253f82463f63a070662d.

We should probably remove as much of the devise configuration as possible from MIRA in favor of whats in tufts_concerns.  Mostly what we'd need from tufts_concerns are the spec_helper and tufts_ldap.ldif changes

**ACCEPTANCE**
- [ ] running `SPEC_OPTS="" bundle exec rake ci` does not result in any LDAP service errors like "Net::LDAP::Error:  Server localhost refused connection on port 3389."

**Comment by little9** [comment]
After adding this I can run:
`SPEC_OPTS="" bundle exec rake ci | grep 'LDAP' ` and I don't get any LDAP tests that fail.

**Comment by mark-dce** [comment]
Fixed by #80
