### ISSUE TITLE
Start a Hyrax Codebase for Initial Development

### ISSUE THREAD

**Issue by no-reply** [curationexperts/MIRA#9]
This will be an app aiming to run against the Fedora 4 instance in #8.

Setup a basic greenfield project.

**Comment by no-reply** [comment]
We'll want to report back on whether Hyrax is the appropriate Hydra dependency.

**Comment by mark-dce** [comment]
Seems like we reached consensus on this one today on our call with Mike K.  Let's plan on moving forward with https://github.com/curationexperts/epigaea
